# tasks file for 6571
- name: resoconto in file {{ logfile }}
  shell: echo "Applicato il bug {{bug}} dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
  delegate_to: localhost
  changed_when: false
- name: resoconto in database ansible
  shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
  delegate_to: localhost
  changed_when: false

- name: Trovo il server con LDAP master
  include: ../roles/6520/tasks/trova_master.yml

  # sul server ansible viene settato un fact in cui ldap_master è l'inventory_hostname del server che detiene il master LDAP

- name: Modifico LDAP MASTER
  include: include/modifica_ldap_master.yml
  when: inventory_hostname == hostvars['localhost']['ldap_master']

# da adesso in poi lavoro su tutti i server e se trovo le mie applicazioni di riferimento ne eseguo il riavvio

- name: riavvio delle applicazioni necessarie
  include: "include/riavvia_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
