- name: recupero i dati di LDAP
  include: ../roles/6520/tasks/dati_inserimento_ldap.yml

# A seguito di questa chiamata ho trovato questi dati:
# rootdn_6520
# rootdpw_6520
# rootdom_6520
# roottld_6520

- name: estraggo l'ultimo file di backup
  shell: ls -1tr /var/ldap/backup/openldap-data*.ldif.gz | tail -1
  changed_when: false
  failed_when: false
  check_mode: false
  register: lastbackup

- name: estraggo tutte le applicazioni di tipo [0-9]@SIPRP
  shell: "zcat {{ lastbackup.stdout }} | unldif | grep -i \"^dn\: cn=[0-9]@SIPRP\" | awk '{print $2}'"
  environment:
               PATH: "{{ ansible_env.PATH }}:/opt/reitek/ct6/bin"
  changed_when: false
  failed_when: false
  check_mode: false
  register: siprps

- name: estraggo tutte le applicazioni di tipo [0-9]@B2BUAVXML
  shell: "zcat {{ lastbackup.stdout }} | unldif | grep -i \"^dn\: cn=[0-9]@B2BUAVXML\" | awk '{print $2}'"
  environment:
               PATH: "{{ ansible_env.PATH }}:/opt/reitek/ct6/bin"
  changed_when: false
  failed_when: false
  check_mode: false
  register: b2buavxmls
